// Domain types for the Bristol Paleo Modelling Group site.
//
// These replace the types that used to be generated by Prisma from the
// database schema. The site now reads everything from files in `content/`
// at build time, so these describe the *parsed* shape of that content.

export type Membership = "CURRENT" | "OLD_FRIEND";

export type MemberRole = "PI" | "POSTDOC" | "PGR" | "VISITOR";

export interface Person {
  /** Stable id (the file name without extension). Used as a React key. */
  id: string;
  slug: string;
  name: string;
  membership: Membership;
  /** null for old friends */
  role: MemberRole | null;
  /** e.g. "Professor of Palaeoclimatology" */
  title: string | null;
  /** short prose bio (the Markdown file body) */
  bio: string | null;
  /** absolute path under /public, e.g. "/images/people/alex-rivers.webp" */
  photoUrl: string | null;
  email: string | null;
  /** primary personal site; for old friends, "now at …" link */
  externalUrl: string | null;
  /** { website, scholar, orcid, twitter, github } */
  links: Record<string, string> | null;
  order: number;
  active: boolean;
}

export interface Publication {
  id: string;
  title: string;
  authors: string;
  venue: string | null;
  year: number;
  doi: string | null;
  url: string | null;
  featured: boolean;
}

export interface GroupMeeting {
  id: string;
  /** ISO date string, e.g. "2026-07-01" */
  date: string;
  speaker: string;
  affiliation: string | null;
  title: string | null;
  abstract: string | null;
  location: string | null;
  isExternal: boolean;
}

export interface EventPhoto {
  id: string;
  imageUrl: string;
  caption: string | null;
}

export interface SocialEvent {
  id: string;
  slug: string;
  title: string;
  date: string;
  description: string | null;
  photos: EventPhoto[];
}

export interface Vacancy {
  id: string;
  slug: string;
  title: string;
  /** Markdown body */
  body: string;
  kind: string | null;
  /** ISO date string */
  closingDate: string | null;
  applyUrl: string | null;
  active: boolean;
  postedAt: string;
}

export interface PageContent {
  title: string;
  body: string;
}
